# Generated by Django 4.1 on 2022-09-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_alter_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created', 'title']},
        ),
    ]
