# Generated by Django 4.1 on 2022-09-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created']},
        ),
    ]
