# Generated by Django 4.1 on 2022-09-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created', 'title', 'state']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='state',
        ),
    ]
