# Generated by Django 4.1 on 2022-09-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_alter_post_options_rename_is_published_post_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created', 'title', 'state']},
        ),
    ]
